### ISSUE TITLE
Add your feedback about the Live Stream.

### ISSUE THREAD

**Issue by praveenscience** [praveenscience/intro-to-open-source-gdsc#1]
The ReadMe has to be updated with some info about how you understood or found the Live Stream.

**Comment by rucha0702** [comment]
Hey! Can I some feedback?

**Comment by RitikaGarg-tech** [comment]
I want to add something.

**Comment by praveenscience** [comment]
@rucha0702 Yes, please go ahead and start your contirbution.

**Comment by praveenscience** [comment]
@RitikaGarg-tech You too can start contribution.

**Comment by setco-website** [comment]
I would like to also contribute to this repo.

**Comment by praveenscience** [comment]
@setco-website Go ahead and raise a PR.

**Comment by shray-jayn** [comment]
Hello ! 
I represent the "Flat Earth Society".
